# keras를 이용한 linear_regression

- toc:true
- branch: master
- badges: true
- comments: true
- author: 



## 13_1_keras_linear_regression



In [2]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

- linear_regression 함수 생성

In [4]:
def linear_regression():
  x = [[1],
       [2],
       [3]]

  y = [[1],
       [2],
       [3]]

# predict 생성
  model = keras.Sequential()              # 순서대로 layer를 쌓아가는 모델
  model.add(keras.layers.Dense(1))        # output layer 개수로 지정한다.

# optimizer, loss 생성
  model.compile(optimizer = keras.optimizers.SGD(0.1),
                loss = keras.losses.mse)
  
  model.fit(x, y, epochs = 10, verbose = 2)  # verbose(0: 출력 x, 1: 전부출력, 2: 일부출력)
  print('mse:', model.evaluate(x, y, verbose=0))

  print(model.predict(x))

# x = 5, 7일 때 y 예측

  print(model.predict([[5],
                      [7]])) 

linear_regression()

Epoch 1/10
1/1 - 0s - loss: 23.8470 - 198ms/epoch - 198ms/step
Epoch 2/10
1/1 - 0s - loss: 0.3785 - 6ms/epoch - 6ms/step
Epoch 3/10
1/1 - 0s - loss: 0.0937 - 7ms/epoch - 7ms/step
Epoch 4/10
1/1 - 0s - loss: 0.0861 - 8ms/epoch - 8ms/step
Epoch 5/10
1/1 - 0s - loss: 0.0820 - 6ms/epoch - 6ms/step
Epoch 6/10
1/1 - 0s - loss: 0.0781 - 7ms/epoch - 7ms/step
Epoch 7/10
1/1 - 0s - loss: 0.0744 - 7ms/epoch - 7ms/step
Epoch 8/10
1/1 - 0s - loss: 0.0708 - 10ms/epoch - 10ms/step
Epoch 9/10
1/1 - 0s - loss: 0.0675 - 7ms/epoch - 7ms/step
Epoch 10/10
1/1 - 0s - loss: 0.0643 - 7ms/epoch - 7ms/step
mse: 0.06121388077735901
[[1.3658723]
 [2.0785158]
 [2.7911594]]
[[4.2164464]
 [5.6417336]]


- cars 프로젝트

In [5]:
import pandas as pd

In [25]:
def linear_regression_cars():
  cars = pd.read_csv('/content/cars.csv')

  x = cars.values[:,-1].reshape([-1,1])
  y = cars.values[:, -1:]

  print(x.shape, y.shape)

  model = keras.Sequential()
  model.add(keras.layers.Dense(1))

  model.compile(optimizer = keras.optimizers.SGD(0.001),
                loss = keras.losses.mse)
  
  model.fit(x, y, epochs = 10, verbose = 2)

  print('mse:', model.evaluate(x, y, verbose = 0))

  p = model.predict([[0],
                    [40]])
  print(p)


In [26]:
linear_regression_cars()

(50, 1) (50, 1)
Epoch 1/10
2/2 - 0s - loss: 49522.4414 - 208ms/epoch - 104ms/step
Epoch 2/10
2/2 - 0s - loss: 15688008.0000 - 10ms/epoch - 5ms/step
Epoch 3/10
2/2 - 0s - loss: 4629734912.0000 - 7ms/epoch - 3ms/step
Epoch 4/10
2/2 - 0s - loss: 1032738504704.0000 - 8ms/epoch - 4ms/step
Epoch 5/10
2/2 - 0s - loss: 168208048848896.0000 - 8ms/epoch - 4ms/step
Epoch 6/10
2/2 - 0s - loss: 52226544621322240.0000 - 7ms/epoch - 4ms/step
Epoch 7/10
2/2 - 0s - loss: 14645528966836781056.0000 - 8ms/epoch - 4ms/step
Epoch 8/10
2/2 - 0s - loss: 3239783737339091615744.0000 - 7ms/epoch - 4ms/step
Epoch 9/10
2/2 - 0s - loss: 1040827486342347633983488.0000 - 8ms/epoch - 4ms/step
Epoch 10/10
2/2 - 0s - loss: 267117468816796729760284672.0000 - 8ms/epoch - 4ms/step
mse: 8.870804287314401e+27
[[-3.7911986e+10]
 [-7.5389024e+13]]
